Repository hmcts/ccpay-service-request-cpo-update-service, pull requests merged in 2022-09, with the labels that each got.

#113 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-113

#120 Extend cve suppressions
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-120

#124 updated suppression file
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-124
