Repository hmcts/ccpay-service-request-cpo-update-service, pull requests merged in 2023-02, with the labels that each got.

#156 cve fix
  build.gradle
  charts/ccpay-cpo-update-service/Chart.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-156

#160 cve fix
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-160

#162 suppressing cve, no fix available
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-162
