Repository hmcts/ccpay-service-request-cpo-update-service, pull requests merged in 2023-01, with the labels that each got.

#145 upgrade netty version for cve
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-145

#147 cve fix
  config/owasp/suppressions.xml
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-cpo-update-service-pr-147

#153 Upgraded Terraform version to 1.3.7
  infrastructure/.terraform-version
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-cpo-update-service-pr-153
